'use client';
import { FormEvent,useEffect,useState } from 'react';
import { useRouter } from 'next/navigation';
import { supabaseBrowser } from '@/lib/supabase';

type Student={id:string;full_name:string;username:string;gender:string}; type Row={id:number;student_id:string;tanggal:string;setoran:string;ziyadah:string;murojaah:string;halaqoh:string;tahsin:string;catatan:string};
const empty={tanggal:new Date().toISOString().slice(0,10),setoran:'',ziyadah:'',murojaah:'',halaqoh:'',tahsin:'',catatan:''};
export default function Pengampu(){
 const router=useRouter();const s=supabaseBrowser();const [me,setMe]=useState('');const [students,setStudents]=useState<Student[]>([]);const [rows,setRows]=useState<Row[]>([]);const [selected,setSelected]=useState<Student|null>(null);const [form,setForm]=useState(empty);const [search,setSearch]=useState('');const [editId,setEditId]=useState<number|null>(null);const [loading,setLoading]=useState(true);const [msg,setMsg]=useState('');
 async function loadRows(studentId:string){const {data}=await s.from('mutabaah').select('*').eq('student_id',studentId).order('tanggal',{ascending:false});setRows(data??[]);}
 useEffect(()=>{(async()=>{const {data:user}=await s.auth.getUser();if(!user.user){router.replace('/login');return;}const {data:p}=await s.from('profiles').select('full_name,role').eq('id',user.user.id).single();if(!p||p.role!=='pengampu'){router.replace('/dashboard');return;}setMe(p.full_name);const {data:st}=await s.from('profiles').select('id,full_name,username,gender').eq('role','mahasiswa').order('full_name');setStudents(st??[]);setLoading(false);})();},[]);
 function choose(st:Student){setSelected(st);setEditId(null);setForm({...empty});setMsg('');loadRows(st.id);}
 function edit(r:Row){setEditId(r.id);setForm({tanggal:r.tanggal,setoran:r.setoran??'',ziyadah:r.ziyadah??'',murojaah:r.murojaah??'',halaqoh:r.halaqoh??'',tahsin:r.tahsin??'',catatan:r.catatan??''});window.scrollTo({top:0,behavior:'smooth'});}
 async function save(e:FormEvent){e.preventDefault();if(!selected)return;setMsg('Menyimpan…');const payload={student_id:selected.id,...form};const res=editId?await s.from('mutabaah').update(payload).eq('id',editId):await s.from('mutabaah').insert(payload);if(res.error){setMsg(res.error.message);return;}setMsg('Tersimpan.');setEditId(null);setForm(empty);loadRows(selected.id);}
 async function logout(){await s.auth.signOut();router.replace('/login');}
 const filtered=students.filter(x=>(x.full_name+' '+x.username).toLowerCase().includes(search.toLowerCase()));
 if(loading)return <main className="center"><div className="card">Memuat dashboard pengampu…</div></main>;
 return <main className="shell"><header className="topbar"><div><p className="eyebrow">MUTABA’AH RUMUZ · PENGAMPU</p><h2>{me}</h2></div><button className="ghost" onClick={logout}>Keluar</button></header><div className="layout"><aside className="card sidebar"><input placeholder="Cari mahasiswa…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="count">{filtered.length} mahasiswa</div>{filtered.map(st=><button key={st.id} className={'student-item '+(selected?.id===st.id?'active':'')} onClick={()=>choose(st)}><strong>{st.full_name}</strong><span>{st.gender} · @{st.username}</span></button>)}</aside><section><div className="hero compact"><div><span className="pill">AKSES SELURUH MAHASISWA</span><h1>{selected?selected.full_name:'Pilih mahasiswa'}</h1><p>{selected?'Kelola riwayat mutaba’ah mahasiswa ini.':'Pilih nama di sebelah kiri untuk mulai.'}</p></div></div>{selected&&<><form onSubmit={save} className="card form-card"><h3>{editId?'Edit Mutaba’ah':'Input Mutaba’ah'}</h3><div className="grid-form"><label>Tanggal<input type="date" value={form.tanggal} onChange={e=>setForm({...form,tanggal:e.target.value})}/></label><label>Setoran<input value={form.setoran} onChange={e=>setForm({...form,setoran:e.target.value})}/></label><label>Ziyadah<input value={form.ziyadah} onChange={e=>setForm({...form,ziyadah:e.target.value})}/></label><label>Muroja’ah<input value={form.murojaah} onChange={e=>setForm({...form,murojaah:e.target.value})}/></label><label>Halaqoh<input value={form.halaqoh} onChange={e=>setForm({...form,halaqoh:e.target.value})}/></label><label>Tahsin<input value={form.tahsin} onChange={e=>setForm({...form,tahsin:e.target.value})}/></label><label className="full">Catatan<textarea value={form.catatan} onChange={e=>setForm({...form,catatan:e.target.value})}/></label></div><div className="actions"><button className="primary">{editId?'Simpan Perubahan':'Simpan Mutaba’ah'}</button>{editId&&<button type="button" className="ghost" onClick={()=>{setEditId(null);setForm(empty)}}>Batal</button>}</div>{msg&&<p className="muted">{msg}</p>}</form><div className="card table-wrap"><table><thead><tr><th>Tanggal</th><th>Setoran</th><th>Ziyadah</th><th>Muroja’ah</th><th>Halaqoh</th><th>Tahsin</th><th>Catatan</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.tanggal}</td><td>{r.setoran}</td><td>{r.ziyadah}</td><td>{r.murojaah}</td><td>{r.halaqoh}</td><td>{r.tahsin}</td><td>{r.catatan}</td><td><button className="link-btn" onClick={()=>edit(r)}>Edit</button></td></tr>)}{!rows.length&&<tr><td colSpan={8} className="empty">Belum ada data.</td></tr>}</tbody></table></div></>}</section></div></main>;
}
