create extension if not exists "pgcrypto";

drop table if exists public.mutabaah cascade;
drop table if exists public.profiles cascade;

do $$ begin create type public.user_role as enum ('mahasiswa','pengampu','admin'); exception when duplicate_object then null; end $$;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  username text unique not null,
  email text unique not null,
  role public.user_role not null default 'mahasiswa',
  gender text not null check (gender in ('Ikhwan','Akhwat')),
  created_at timestamptz not null default now()
);

create table public.mutabaah (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  tanggal date not null,
  setoran text not null default '',
  ziyadah text not null default '',
  murojaah text not null default '',
  halaqoh text not null default '',
  tahsin text not null default '',
  catatan text not null default '',
  updated_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index mutabaah_student_date_idx on public.mutabaah(student_id,tanggal desc);

alter table public.profiles enable row level security;
alter table public.mutabaah enable row level security;

create or replace function public.current_role() returns public.user_role language sql stable security definer set search_path=public as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.touch_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
drop trigger if exists mutabaah_touch on public.mutabaah;
create trigger mutabaah_touch before update on public.mutabaah for each row execute function public.touch_updated_at();

create policy "profiles own read" on public.profiles for select to authenticated using (id=auth.uid());
create policy "pengampu read student profiles" on public.profiles for select to authenticated using (public.current_role() in ('pengampu','admin'));

create policy "student read own mutabaah" on public.mutabaah for select to authenticated using (student_id=auth.uid());
create policy "pengampu read all mutabaah" on public.mutabaah for select to authenticated using (public.current_role() in ('pengampu','admin'));
create policy "pengampu insert mutabaah" on public.mutabaah for insert to authenticated with check (public.current_role() in ('pengampu','admin') and student_id in (select id from public.profiles where role='mahasiswa'));
create policy "pengampu update all mutabaah" on public.mutabaah for update to authenticated using (public.current_role() in ('pengampu','admin')) with check (public.current_role() in ('pengampu','admin'));
create policy "admin delete mutabaah" on public.mutabaah for delete to authenticated using (public.current_role()='admin');

create or replace function public.find_login_email(p_username text) returns table(email text) language sql security definer set search_path=public as $$
  select p.email from public.profiles p where p.username = lower(trim(p_username)) limit 1;
$$;
grant execute on function public.find_login_email(text) to anon, authenticated;

grant usage on schema public to authenticated;
grant select on public.profiles to authenticated;
grant select,insert,update,delete on public.mutabaah to authenticated;
